# Generated by Django 4.1 on 2022-09-19 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hydrometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('macadress', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('ssid', models.CharField(max_length=100)),
                ('password_ssid', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('read_state', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.client')),
            ],
            options={
                'db_table': 'hydrometer',
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowrate', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.client')),
                ('hydrometer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.hydrometer')),
            ],
            options={
                'db_table': 'meter',
            },
        ),
    ]
