# Generated by Django 4.1 on 2022-09-19 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0002_alter_hydrometer_macadress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrometer',
            name='client',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='accounts.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meter',
            name='client',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='accounts.client'),
            preserve_default=False,
        ),
    ]
