# Generated by Django 4.1 on 2022-09-19 04:48

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gener', models.CharField(max_length=10)),
                ('rg', models.CharField(blank=True, max_length=30)),
                ('cpf', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'client',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.CharField(max_length=30)),
                ('mode', models.CharField(blank=True, max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=10)),
                ('complement', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('state', models.CharField(choices=[('11', 'RO'), ('12', 'AC'), ('13', 'AM'), ('14', 'RR'), ('15', 'PA'), ('16', 'AP'), ('17', 'TO'), ('21', 'MA'), ('22', 'PI'), ('23', 'CE'), ('24', 'RN'), ('25', 'PB'), ('26', 'PE'), ('27', 'AL'), ('28', 'SE'), ('29', 'BA'), ('31', 'MG'), ('32', 'ES'), ('33', 'RJ'), ('35', 'SP'), ('41', 'PR'), ('42', 'SC'), ('43', 'RS'), ('50', 'MS'), ('51', 'MT'), ('52', 'GO'), ('53', 'DF')], default='SP', max_length=2)),
                ('city', models.CharField(default='SP', max_length=200)),
                ('country', models.CharField(max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
            options={
                'db_table': 'client_adress',
            },
        ),
    ]
